//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWpf4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Блюдо
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Блюдо()
        {
            this.Состав_Блюда = new HashSet<Состав_Блюда>();
            this.Состав_Заказа = new HashSet<Состав_Заказа>();
        }
    
        public int Id_Блюдо { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public Nullable<int> Категория { get; set; }
        public string Доступ_для_заказа { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Категория_блюда Категория_блюда { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Блюда> Состав_Блюда { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Заказа> Состав_Заказа { get; set; }
    }
}
