//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWpf4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ингридиента
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ингридиента()
        {
            this.Состав_Блюда = new HashSet<Состав_Блюда>();
        }
    
        public int Id_Ингридиента { get; set; }
        public string Название { get; set; }
        public Nullable<long> Кол_во_на_складе { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Блюда> Состав_Блюда { get; set; }
    }
}
