//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWpf4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_Блюда
    {
        public int Id_Состав_Блюда { get; set; }
        public Nullable<int> Блюдо { get; set; }
        public Nullable<int> Ингридиент { get; set; }
    
        public virtual Блюдо Блюдо1 { get; set; }
        public virtual Ингридиента Ингридиента { get; set; }
    }
}
